#use pkg-config
FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(CONAN_GLIBMM glibmm)
FIND_PATH(glibmm_INCLUDE_DIR NAMES glibmm/main.h PATHS ${CONAN_INCLUDEDIR_GLIBMM} ${CONAN_INCLUDE_DIRS_GLIBMM})
FIND_PATH(glibmm_config_INCLUDE_DIR NAMES glibmmconfig.h PATHS ${CONAN_INCLUDEDIR_GLIBMM} ${CONAN_INCLUDE_DIRS_GLIBMM})
FIND_LIBRARY(glibmm_LIBRARY NAMES glibmm glibmm PATHS ${CONAN_LIBDIR_GLIBMM} ${CONAN_LIBRARY_DIRS_GLIBMM})
SET(glibmm_LIBRARIES ${glibmm_LIBRARY} ${CONAN_PKGCONF_LIBRARIES_GLIBMM} ${glib_LIBRARIES} ${sigc++_LIBRARIES})
SET(glibmm_INCLUDE_DIRS ${glibmm_INCLUDE_DIR} ${glibmm_config_INCLUDE_DIR} ${CONAN_PKGCONF_INCLUDE_DIRS_GLIBMM} ${glib_INCLUDE_DIRS} ${sigc++_INCLUDE_DIRS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(glibmm DEFAULT_MSG glibmm_LIBRARY glibmm_INCLUDE_DIR)

MARK_AS_ADVANCED(glibmm_INCLUDE_DIR glibmm_config_INCLUDE_DIR glibmm_LIBRARY)