#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import path

def load_tools(ctx):
    ctx.load('compiler_cxx')

def options(ctx):
    load_tools(ctx)

def configure(ctx):
    load_tools(ctx)

    ctx.load('conanbuildinfo_waf', tooldir=[".", path.join(ctx.bldnode.abspath(), "..")]);

    ctx.env.CXXFLAGS = ['-std=c++11']

def build(bld):
    bld.program(
        target   = 'test_package',
        source   = "test_package.cpp",
        includes = ['.'],
        use      = bld.env.conan_dependencies)
